### ISSUE TITLE
Question: How do I create pagination for BlogTagSearch

### ISSUE THREAD

**Issue by vosco88** [scottbedard/blogtags#25]
I am trying to work out the pagination for this component, however trying to access the properties does not work for me. I am using `blogTagSearch.property`

I am getting data when accesing `posts, tag, resultsPerPage, postsOnPage, postPage, categoryPage` gives me data. However the rest of them outputs either 0 (`lastPage`, `currentPage`, `totalPosts`) or nothing (`nextPage`, `previousPage`) when trying to use in twig. What I am doing wrong

My component settings:
![image](https://user-images.githubusercontent.com/14372933/74223871-edc41c00-4cb7-11ea-87c7-853be1b81d4b.png)

**Comment by chrisvidal** [comment]
there is a bug in the `calculatePagination` method in this component. I fixed it and create a PR yesterday.
Let's hope @scottbedard will see it soon

**Comment by scottbedard** [comment]
Merged, thanks
