### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by frthjf** [scottbedard/blogtags#4]
Even if "Paginate by page" is disabled an unconfigured page slug leads to a division by zero exception in `october/plugins/bedard/blogtags/components/BlogTagSearch.php line 157`

**Comment by webeks** [comment]
@dudheit  here is a fix if you still need it https://github.com/webeks/blogtags/commit/f446c9eb415d93a7a88e0c17ec7eebfac6fc488a

Will make a PR for this.
