### ISSUE TITLE
pagination for tag list

### ISSUE THREAD

**Issue by acp6** [scottbedard/blogtags#9]
Is it possible to add pagination support for tag list? Just like the pagination for tag search

**Comment by scottbedard** [comment]
The only way to achieve this right now would be to write an additional component, or make the query in your page / partial's `onStart` method. Shouldn't be too difficult, just take a look at the tags query [here](https://github.com/scottbedard/blogtags/blob/master/components/BlogTags.php#L76-L104) and modify it to suit your needs.

Let me know if you need help!
